routes/web.php
<?php

use App\Http\Controllers\ManageController;
use App\Http\Controllers\ManagePermissionController;
use App\Http\Controllers\ManagesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('dashboards', function () {
    return view('admin.layouts.dashboard');
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('posts', PostsController::class);
Route::resource('user', UserController::class)->middleware('role:admin,manager');
Route::resource('roles', RoleController::class)->middleware('can:isAdmin');

Route::resource('teacher', TeacherController::class);
Route::resource('manage_controller', ManagesController::class);
Route::resource('manage_permission', ManagePermissionController::class);
Route::resource('roless', RolesController::class);

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HasRolesAndPermissions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRolesAndPermissions; //add HasRolesAndPermissions

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function index()
    {
        $users = User::orderBy('id', 'desc')->get();
        return view('admin.users.index', ['users' => $users]);

    }


    public function create(Request $request)
    {
        if($request->ajax()){
            $roles = Role::where('id', $request->role_id)->first();
            $permissions = $roles->permissions;

            return $permissions;
        }

        $roles = Role::all();
        return view('admin.users.create', ['roles' => $roles]);
    }


    public function store(Request $request)
    {
        //validate the fields
        $request->validate([
            'name' => 'required|max:255',
            'permissions' => 'required',
            'email' => 'required|unique:users|email|max:255',
            'password' => 'required|between:8,255|confirmed',
            'password_confirmation' => 'required'
        ]);
        // dd($request);
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();

        // save data to User_role
        if($request->role != null){
            $user->roles()->attach($request->role);
            $user->save();
        }

        // save data to User_permission
        if($request->permissions != null){
            foreach ($request->permissions as $permission) {
                $user->permissions()->attach($permission);
                $user->save();
            }
        }

        return redirect()->route('user.index');
    }


    public function show(User $user)
    {
        return view('admin.users.view', ['user' => $user]);
    }


    public function edit(User $user)
    {
        // $this->authorize('edit', $user);
        $roles = Role::get();
        $userRole = $user->roles->first();
        if($userRole != null){
            $rolePermissions = $userRole->allRolePermissions;
        }else{
            $rolePermissions = null;
        }
        $userPermissions = $user->permissions;

        // dd($rolePermission);

        return view('admin.users.edit', [
            'user'=>$user,
            'roles'=>$roles,
            'userRole'=>$userRole,
            'rolePermissions'=>$rolePermissions,
            'userPermissions'=>$userPermissions
            ]);
    }


    public function update(Request $request, User $user)
    {
        //dd($request);
        //validate the fields
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
            'password' => 'confirmed',
        ]);
        // $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password != null){
            $user->password = Hash::make($request->password);
        }
        $user->save();

        $user->roles()->detach();
        $user->permissions()->detach();

        if($request->role != null){
            $user->roles()->attach($request->role);
            $user->save();
        }

        if($request->permissions != null){
            foreach ($request->permissions as $permission) {
                $user->permissions()->attach($permission);
                $user->save();
            }
        }
        return redirect()->route('user.index');
    }


    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->permissions()->detach();
        $user->delete();
        return redirect('/user');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.dashboard')
@push('css')

@endpush
@section('content')
<div class="container-fluid">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List Role</h3>
                <a href="/user" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square"></i>  BACK</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label for="name">User name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Name..." value="{{ old('name') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email..." value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password..." required minlength="8">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Password Confirm</label>
                        <input type="password" name="password_confirmation" class="form-control" placeholder="Password..." id="password_confirmation">
                    </div>
                    <div class="form-group">
                        <label for="role">Select Role</label>
                        <select name="role" id="role" class="form-control">
                            <option value="">Select Role...</option>
                            @foreach($roles as $role)
                                <option data-role-id="{{$role->id}}" data-role-slug="{{$role->slug}}" value="{{ $role->id }}">{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div id="permissions_box" >
                        <label for="roles">Select Permissions</label>
                        <div id="permissions_ckeckbox_list">
                        </div>
                    </div>

                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
    </div>
</div>
@endsection
@push('js')
<script>

    $(document).ready(function(){
        var permissions_box = $('#permissions_box');
        var permissions_ckeckbox_list = $('#permissions_ckeckbox_list');

        permissions_box.hide(); // hide all boxes


        $('#role').on('change', function() {
            var role = $(this).find(':selected');
            var role_id = role.data('role-id');
            var role_slug = role.data('role-slug');

            permissions_ckeckbox_list.empty();

            $.ajax({
                url: "/user/create",
                method: 'get',
                dataType: 'json',
                data: {
                    role_id: role_id,
                    role_slug: role_slug,
                }
            }).done(function(data) {
                console.log(data);

                permissions_box.show();
                // permissions_ckeckbox_list.empty();

                $.each(data, function(index, element){
                    $(permissions_ckeckbox_list).append(
                        '<div class="custom-control custom-checkbox">'+
                            '<input class="custom-control-input" type="checkbox" name="permissions[]" id="'+ element.slug +'" value="'+ element.id +'">' +
                            '<label class="custom-control-label" for="'+ element.slug +'">'+ element.name +'</label>'+
                        '</div>'
                    );

                });
            });
        });
    });

</script>
@endpush

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.dashboard')
@push('css')

@endpush
@section('content')
<div class="container-fluid">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List Role</h3>
                <a href="" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square"></i>  NEW</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('user.update', $user->id) }}" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf()

                    <div class="form-group">
                        <label for="name">User name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Name..." value="{{ $user->name }}" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email..." value="{{ $user->email }}">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password..." minlength="8">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">Password Confirm</label>
                        <input type="password" name="password_confirmation" class="form-control" placeholder="Password..." id="password_confirmation">
                    </div>

                    <div class="form-group">
                        <label for="role">Select Role</label>
                        <select class="role form-control" name="role" id="role">
                            <option value="">Select Role...</option>
                            @foreach ($roles as $role)
                                <option data-role-id="{{$role->id}}" data-role-slug="{{$role->slug}}" value="{{$role->id}}" {{ $user->roles->isEmpty() || $role->name != $userRole->name ? "" : "selected"}}>{{$role->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div id="permissions_box" >
                        <label for="roles">Select Permissions</label>
                        <div id="permissions_ckeckbox_list">
                        </div>
                    </div>

                    @if($user->permissions->isNotEmpty())
                        @if($rolePermissions != null)
                            <div id="user_permissions_box" >
                                <label for="roles">User Permissions</label>
                                <div id="user_permissions_ckeckbox_list">
                                    @foreach ($rolePermissions as $permission)
                                    <div class="custom-control custom-checkbox">
                                        <input class="custom-control-input" type="checkbox" name="permissions[]" id="{{$permission->slug}}" value="{{$permission->id}}" {{ in_array($permission->id, $userPermissions->pluck('id')->toArray() ) ? 'checked="checked"' : '' }}>
                                        <label class="custom-control-label" for="{{$permission->slug}}">{{$permission->name}}</label>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        @endif
                    @endif

                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
    </div>
</div>
@endsection
@push('js')
<script>

    $(document).ready(function(){
        var permissions_box = $('#permissions_box');
        var permissions_ckeckbox_list = $('#permissions_ckeckbox_list');
        var user_permissions_box = $('#user_permissions_box');
        var user_permissions_ckeckbox_list = $('#user_permissions_ckeckbox_list');

        permissions_box.hide(); // hide all boxes


        $('#role').on('change', function() {
            var role = $(this).find(':selected');
            var role_id = role.data('role-id');
            var role_slug = role.data('role-slug');

            permissions_ckeckbox_list.empty();
            user_permissions_box.empty();

            $.ajax({
                url: "/users/create",
                method: 'get',
                dataType: 'json',
                data: {
                    role_id: role_id,
                    role_slug: role_slug,
                }
            }).done(function(data) {

                console.log(data);

                permissions_box.show();
                // permissions_ckeckbox_list.empty();

                $.each(data, function(index, element){
                    $(permissions_ckeckbox_list).append(
                        '<div class="custom-control custom-checkbox">'+
                            '<input class="custom-control-input" type="checkbox" name="permissions[]" id="'+ element.slug +'" value="'+ element.id +'">' +
                            '<label class="custom-control-label" for="'+ element.slug +'">'+ element.name +'</label>'+
                        '</div>'
                    );

                });
            });
        });
    });

</script>
@endpush

resources/views/admin/users/index.blade.php
@extends('admin.layouts.dashboard')
@section('title')
    User
@endsection
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="wrap-list-role">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List Role</h3>
                    <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square"></i>  NEW</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Role</th>
                      <th>Permission</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $key => $user)
                    @if(!\Auth::user()->hasRole('admin') && $user->hasRole('admin')) @continue; @endif
                    <tr {{ Auth::user()->id == $user->id ? 'bgcolor=#ddd' : '' }}>
                        <td>{{ ++$key }}</td>
                        <td>{{ $user['name'] }}</td>
                        <td>{{ $user['email'] }}</td>
                        <td>
                            @if($user->roles->isNotEmpty())
                                @foreach($user->roles as $role)
                                    <span class="badge badge-success">
                                        {{ $role->name }}
                                    </span>
                                @endforeach
                            @endif
                        </td>
                        <td>
                            @if($user->permissions->isNotEmpty())
                                @foreach($user->permissions as $permission)
                                    <span class="badge badge-danger">
                                        {{ $permission->name }}
                                    </span>
                                @endforeach
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('user.show', $user->id) }}" class="btn btn-info btn-xs view"><i class="fas fa-eye"></i></a>
                            {{-- @can('edit', $user) --}}
                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-danger btn-xs edit"><i class="fas fa-edit"></i></a>
                            {{-- @endcan --}}
                            <a href="#" class="btn btn-info btn-xs delete" data-toggle="modal" data-target="#deleteModal" data-userid="{{$user['id']}}">
                            <i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Permission</th>
                        <th>Action</th>
                    </tr>
                    </tfoot>
                  </table>
                  <!-- delete Modal-->
                  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                      <div class="modal-content">
                          <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Are you shure you want to delete this?</h5>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                          </button>
                          </div>
                          <div class="modal-body">Select "delete" If you realy want to delete this user.</div>
                          <div class="modal-footer">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                          <form method="POST" action="">
                              @method('DELETE')
                              @csrf
                              {{-- <input type="hidden" id="user_id" name="user_id" value=""> --}}
                              <a class="btn btn-primary" onclick="$(this).closest('form').submit();">Delete</a>
                          </form>
                          </div>
                      </div>
                      </div>
                  </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
        </div>
    </div>
@endsection
@push('js')
<!-- DataTables -->
<script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>

<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
</script>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var user_id = button.data('userid')

        var modal = $(this)
        // modal.find('.modal-footer #user_id').val(user_id)
        modal.find('form').attr('action','/user/' + user_id);
    })
</script>

@if(Session::has('success'))
    <script>
        toastr.success("{!! Session::get('success') !!}");
    </script>
@endif
@if(Session::has('warning'))
    <script>
        toastr.info("{!! Session::get('warning') !!}");
    </script>
@endif
@endpush

resources/views/admin/users/view.blade.php
@extends('admin.layouts.dashboard')
@push('css')

@endpush
@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Name: {{$user->name}}</h3>
            <h4>Email: {{$user->email}}</h4>
            <h4>Number of Posts: .....</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Role</h5>
            <p class="card-text">
                @if($user->roles->isNotEmpty())
                    @foreach($user->roles as $role)
                        <span class="badge badge-success">
                            {{ $role->name }}
                        </span>
                    @endforeach
                @endif
            </p>
            <h5 class="card-title">Permissions</h5>
            <p class="card-text">
                @if($user->permissions->isNotEmpty())
                    @foreach($user->permissions as $permission)
                        <span class="badge badge-danger">
                            {{ $permission->name }}
                        </span>
                    @endforeach
                @endif
            </p>

        </div>
        <div class="card-footer">
            <a href="{{ route('user.index')}}" class="btn btn-primary">Go Back</a>
            {{-- <a href="{{ url()->previous() }}" class="btn btn-primary">Go Back</a> --}}
        </div>
    </div>
</div>
@endsection
@push('js')

@endpush