routes/web.php
<?php

use App\Http\Controllers\ManageController;
use App\Http\Controllers\ManagePermissionController;
use App\Http\Controllers\ManagesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('dashboards', function () {
    return view('admin.layouts.dashboard');
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('posts', PostsController::class);
Route::resource('user', UserController::class)->middleware('role:admin,manager');
Route::resource('roles', RoleController::class)->middleware('can:isAdmin');

Route::resource('teacher', TeacherController::class);
Route::resource('manage_controller', ManagesController::class);
Route::resource('manage_permission', ManagePermissionController::class);
Route::resource('roless', RolesController::class);

resources/views/admin/manage_controller/create.blade.php
@extends('admin.layouts.dashboard')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/dist/css/bootstrap-tagsinput.css') }}">
@endpush

@section('content')

<div class="container-fluid">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List manage Controller</h3>
                <a href="{{ route('manage_controller.index') }}" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square"></i>  Back</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('manage_controller.store') }}">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label for="name">Manage Controller</label>
                        <input type="text" name="manage_name" class="form-control" id="manage_name" placeholder="manage name..." value="{{ old('name') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="role_slug">Role Slug</label>
                        <input type="text" name="manage_slug" tag="manage_slug" class="form-control" id="manage_slug" placeholder="manage  Slug..." value="{{ old('manage_slug') }}" required>
                    </div>
                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
          <!-- /.card -->
    </div>
</div>

@endsection
@push('js')
<script src="{{ asset('backend/dist/js/bootstrap-tagsinput.js') }}"></script>

<script>

    $(document).ready(function(){
        $('#manage_name').keyup(function(e){
            var str = $('#manage_name').val();
            str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
            $('#manage_slug').val(str);
            $('#manage_slug').attr('placeholder', str);
        });
    });

</script>
@endpush

resources/views/admin/manage_controller/edit.blade.php
@extends('admin.layouts.dashboard')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/dist/css/bootstrap-tagsinput.css') }}">
@endpush

@section('content')


<div class="container-fluid">
    <h1>Update the ManageController</h1>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List Role</h3>
                <a href="{{ route('manage_controller.index') }}" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square"></i>  Back</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('manage_controller.update', $manageCon->id) }}">
                    @csrf
                    @method('PATCH')

                    <div class="form-group">
                        <label for="name">Manage Controller</label>
                        <input type="text" name="manage_name" class="form-control" id="manage_name" placeholder="manage name..." value="{{$manageCon->name}}" required>
                    </div>
                    <div class="form-group">
                        <label for="role_slug">Role Slug</label>
                        <input type="text" name="manage_slug" tag="manage_slug" class="form-control" id="manage_slug" placeholder="manage  Slug..."  value="{{$manageCon->slug}}" required>
                    </div>
                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
    </div>
</div>

@endsection
@push('js')
<script src="{{ asset('backend/dist/js/bootstrap-tagsinput.js') }}"></script>

<script>
    $(document).ready(function(){
        $('#manage_name').keyup(function(e){
            var str = $('#manage_name').val();
            str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
            $('#manage_slug').val(str);
            $('#manage_slug').attr('placeholder', str);
        });
    });

</script>
@endpush

resources/views/admin/manage_controller/index.blade.php
@extends('admin.layouts.dashboard')
@section('title')
    Manage Controller
@endsection
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/toastr/css/toastr.min.css') }}">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="wrap-list-role">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List Manage Controller</h3>
                    <a href="{{ route('manage_controller.create') }}" class="btn btn-primary btn-xs float-right"><i class="fas fa-plus-square"></i>  NEW</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>

                      <th>Created By</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($manageCon as $key => $manage)

                    <tr>
                        <td>{{ ++$key }}</td>
                        <td>{{ $manage['name'] }}</td>
                        <td>
                            {{ $manage->created_name }}
                        </td>
                        <td>

                            <a href="{{ route('manage_controller.edit', $manage->id) }}" class="btn btn-danger btn-xs edit"><i class="fas fa-edit"></i> Edit</a>
                            <a href="#" class="btn btn-info btn-xs delete" data-toggle="modal" data-target="#deleteModal" data-roleid="{{$manage['id']}}">
                            <i class="fas fa-trash-alt"> Delete</i></a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                      <th>Name</th>

                      <th>Created By</th>
                      <th>Action</th>
                    </tr>
                    </tfoot>
                  </table>
                  <!-- delete Modal-->
                  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                      <div class="modal-content">
                          <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Are you shure you want to delete this?</h5>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                          </button>
                          </div>
                          <div class="modal-body">Select "delete" If you realy want to delete this role.</div>
                          <div class="modal-footer">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                          <form method="POST" action="">
                              @method('DELETE')
                              @csrf
                              {{-- <input type="hidden" id="role_id" name="role_id" value=""> --}}
                              <a class="btn btn-primary" onclick="$(this).closest('form').submit();">Delete</a>
                          </form>
                          </div>
                      </div>
                      </div>
                  </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
        </div>
    </div>
@endsection
@push('js')
<!-- DataTables -->
<script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/toastr/js/toastr.min.js') }}"></script>
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
</script>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var role_id = button.data('roleid')

        var modal = $(this)
        // modal.find('.modal-footer #role_id').val(role_id)
        modal.find('form').attr('action','/manage_controller/' + role_id);
    })
</script>

@if(Session::has('success'))
    <script>
        toastr.success("{!! Session::get('success') !!}");
    </script>
@endif
@if(Session::has('warning'))
    <script>
        toastr.info("{!! Session::get('warning') !!}");
    </script>
@endif
@endpush

resources/views/admin/manage_controller/view.blade.php
@extends('admin.layouts.dashboard')

@section('content')

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Name: {{$role['name']}}</h3>
            <h4>Slug: {{$role['slug']}}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Permissions</h5>
            <p class="card-text">
                ...........
            </p>
        </div>
        <div class="card-footer">

            <a href="{{ route('roles.index')}}" class="btn btn-primary">Go Back</a>
        </div>
    </div>
</div>

@endsection