routes/web.php
<?php

use App\Http\Controllers\ManageController;
use App\Http\Controllers\ManagePermissionController;
use App\Http\Controllers\ManagesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('dashboards', function () {
    return view('admin.layouts.dashboard');
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('posts', PostsController::class);
Route::resource('user', UserController::class)->middleware('role:admin,manager');
Route::resource('roles', RoleController::class)->middleware('can:isAdmin');

Route::resource('teacher', TeacherController::class);
Route::resource('manage_controller', ManagesController::class);
Route::resource('manage_permission', ManagePermissionController::class);
Route::resource('roless', RolesController::class);

resources/views/admin/roless/create.blade.php
@extends('admin.layouts.dashboard')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/dist/css/bootstrap-tagsinput.css') }}">
@endpush

@section('content')

<div class="container-fluid">
    {{-- @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif --}}
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List manage Roles</h3>
                <a href="{{ route('roless.index') }}" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square" ></i>  Back</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('roless.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Manage Roles Name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="manage roles name..." value="{{ old('name') }}" >
                    </div>
                    <hr>
                    <h4>permission</h4>
                    @foreach($manage_controllers as $item)
                        <div class="row">
                            <div class="col-md-6">
                                {{ $item->name }}
                            </div>
                            <div class="col-md-6">
                                <?php
                                $filtered = collect($actions)->where('controller_id', $item->id)->all();
                                ?>
                                @foreach($filtered as $action)
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="checkbox" name="permission[{{ $action->id }}]"
                                            id="permission_[{{ $action->id }}]" class="status">
                                            <label for="permission_[{{ $action->id }}]" class="roleActionlabel">{{ $action->name }}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <hr>
                    @endforeach
                    <hr>
                    <div class="form-group">
                        <label>
                            <input type="checkbox" id="status" class="status" name="status" checked>
                            Publish
                        </label>
                    </div>
                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
          <!-- /.card -->
    </div>
</div>

@endsection
@push('js')
<script src="{{ asset('backend/dist/js/bootstrap-tagsinput.js') }}"></script>

<script>

    $(document).ready(function(){
        $('#permission_name').keyup(function(e){
            var str = $('#permission_name').val();
            str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
            $('#permission_slug').val(str);
            $('#permission_slug').attr('placeholder', str);
        });
    });

</script>
@endpush

resources/views/admin/roless/edit.blade.php
@extends('admin.layouts.dashboard')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/dist/css/bootstrap-tagsinput.css') }}">
@endpush

@section('content')

<div class="container-fluid">
    {{-- @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif --}}
    <div class="wrap-list-role">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Edit manage Roles</h3>
                <a href="{{ route('roless.index') }}" class="btn btn-primary btn-sm float-right"><i class="fas fa-plus-square" ></i>  Back</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form method="POST" action="{{ route('roless.update', $roless->id) }}">
                    {{ csrf_field() }}
                    @method('put')
                    <div class="form-group">
                        <label for="name">Manage Roles Name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="manage roles name..." value="{{ $roless->name }}">
                    </div>
                    <hr>
                    <h4>permission</h4>
                    @foreach($manage_controllers as $item)
                        <div class="row">
                            <div class="col-md-6">
                                {{ $item->name }}
                            </div>
                            <div class="col-md-6">
                                <?php
                                $filtered = collect($actions)->where('controller_id', $item->id)->all();
                                ?>
                                @foreach($filtered as $action)
                                    <?php
                                        $check = '';
                                        foreach ($role_permission as $val){
                                            if($val['permission_id'] == $action->id){
                                                $check = 'checked';
                                            }
                                        }

                                    ?>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="checkbox" name="permission[{{ $action->id }}]" id="permission_[{{ $action->id }}]" class="status" {{ $check }}>
                                            <label for="permission_[{{ $action->id }}]">{{ $action->name }}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <hr>
                    @endforeach
                    <hr>
                    <div class="form-group">
                        <label>
                            <input type="checkbox" id="status" class="status" name="status" {{ $roless->status == 1?'checked':'' }}>
                            Publish
                        </label>
                    </div>
                    <div class="form-group pt-2">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
          <!-- /.card -->
    </div>
</div>

@endsection
@push('js')
<script src="{{ asset('backend/dist/js/bootstrap-tagsinput.js') }}"></script>

<script>

    $(document).ready(function(){
        $('#permission_name').keyup(function(e){
            var str = $('#permission_name').val();
            str = str.replace(/\W+(?!$)/g, '-').toLowerCase();//rplace stapces with dash
            $('#permission_slug').val(str);
            $('#permission_slug').attr('placeholder', str);
        });
    });

</script>
@endpush

resources/views/admin/roless/index.blade.php
@extends('admin.layouts.dashboard')
@section('title')
    Manage Rolss
@endsection
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/toastr/css/toastr.min.css') }}">
@endpush
@section('content')
    <div class="container-fluid">
        <div class="wrap-list-role">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List Manage Controller</h3>
                    <a href="{{ route('roless.create') }}" class="btn btn-primary btn-xs float-right"><i class="fas fa-plus-square"></i>  NEW</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Role Name</th>
                      <th>Created By</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($roless as $key => $roles)

                    <tr>
                        <td>{{ ++$key }}</td>
                        <td>{{ $roles['name'] }}</td>
                        <td>
                            {{ $roles->created_name }}
                        </td>
                        <td>
                            <a href="{{ route('roless.edit', $roles->id) }}" class="btn btn-info btn-xs edit"><i class="fas fa-edit"></i> Edit</a>
                            <a href="javascript:deleteObject({{ $roles->id }})" class="btn btn-danger btn-xs delete"><i class="fa fa-trash-o"> Delete</i></a>
                                <form id="frmDeleteObject-{{ $roles->id }}" style="display: none" action="{{ route('roless.destroy',$roles->id) }}" role="form" method="POST" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Role Name</th>
                        <th>Created By</th>
                        <th>Action</th>
                        </tr>
                    </tfoot>
                  </table>

                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
        </div>
    </div>
@endsection
@push('js')
<!-- DataTables -->
<script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/sweetalert2/js/sweetalert2.min.js') }}"></script>
<script src="{{ asset('backend/sweetalert2/js/sweetalert2@10.js') }}"></script>
<script src="{{ asset('backend/toastr/js/toastr.min.js') }}"></script>
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
</script>
<script type="text/javascript">
    function deleteObject(id){
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          document.getElementById('frmDeleteObject-'+id).submit();
          Swal.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          )
        }
      })
    }
</script>

@if(Session::has('success'))
    <script>
        toastr.success("{!! Session::get('success') !!}");
    </script>
@endif
@if(Session::has('warning'))
    <script>
        toastr.info("{!! Session::get('warning') !!}");
    </script>
@endif
@endpush